name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install alpaca-trade-api==3.0.0
          pip install "websockets>=14.0"
          pip install pandas==2.3.3 numpy==2.2.6 ta==0.11.0 feedparser==6.0.12
          pip install scikit-learn==1.7.2 xgboost==3.2.0
          pip install stable-baselines3==2.8.0 gymnasium==1.2.3
          pip install torch==2.11.0 --index-url https://download.pytorch.org/whl/cpu
          pip install vectorbt==0.28.5 streamlit==1.56.0 plotly==6.7.0
          pip install APScheduler==3.11.2 python-dotenv==1.2.2 pytest==9.0.3
          pip install google-genai==1.73.0 textblob==0.20.0
          pip install polygon-api-client==1.16.3

      - name: Run tests
        run: python -m pytest tests/ -v
        env:
          POLYGON_API_KEY: test_key
          ALPACA_API_KEY: test_key
          ALPACA_SECRET_KEY: test_key


#using test keys because github actions doesn't use env files, so the polygon client would crash at improt if we didn't have test keys (for test_backetesting.py)